services:
  hocuspocus:
    build:
      context: ./server
      dockerfile: Dockerfile.hocuspocus
    ports:
      - "1234:1234"
    environment:
      NODE_ENV: production
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      HOCUSPOCUS_PORT: 1234
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
    restart: unless-stopped

  signaling:
    build:
      context: ./server
      dockerfile: Dockerfile.signaling
    ports:
      - "4444:4444"
    environment:
      NODE_ENV: production
      SIGNALING_PORT: 4444
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
    restart: unless-stopped

