version: '3.8'

services:
  hocuspocus:
    build:
      context: .
      dockerfile: Dockerfile.hocuspocus
    ports:
      - "1234:1234"
    environment:
      - NODE_ENV=production
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - HOCUSPOCUS_PORT=1234
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
    restart: unless-stopped

  signaling:
    build:
      context: .
      dockerfile: Dockerfile.signaling
    ports:
      - "4444:4444"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - NODE_ENV=production
      - SIGNALING_PORT=4444
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
    restart: unless-stopped

